apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        - name: prometheus
          command: ["/bin/prometheus"]
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/input/prometheus"
            - "--storage.tsdb.retention.time=2y"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
          image: prometheus:latest
          ports:
            - name: prometheus
              containerPort: 9090
          volumeMounts:
            - name: promdata
              mountPath: /input
      volumes:
        - name: promdata
        # Details for the volume must be set in an overlay
