apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: prometheus
      port: 9090
      targetPort: 9090
