apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: trimmed-prometheus
namePrefix: trimmed-
resources:
  - ../../base/prometheus
  - pvc.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes
        value:
          - name: promdata
            persistentVolumeClaim:
              claimName: trimmed-prometheus
    target:
      group: apps
      version: v1
      kind: Deployment
