apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: promextractor
resources:
  - ../00_normal
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/command
        value: ["sleep"]
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["7200"]
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: "app.kubernetes.io/component=dump-target"
