apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: extractor
resources:
  - ../../base/extractor
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes
        value:
          - name: input
            persistentVolumeClaim:
              claimName: dump-target-prometheus
          - name: output
            persistentVolumeClaim:
              claimName: trimmed-prometheus
    target:
      group: batch
      version: v1
      kind: Job
