apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: promextractor
resources:
  - ../../with-pvcs/dump-target-prometheus
  - ../../with-pvcs/trimmed-prometheus
images:
  - name: prometheus
    newName: docker.io/prom/prometheus
    newTag: v2.47.2
